import { UiInputProperty } from "../../abstract/ui-input-property";

export class FilterStaticData {
    static readonly FilterTypes: UiInputProperty[] =
        [
            { name: 'And', value: 'and' },
            { name: 'Or', value: 'or' },
        ];
    static readonly FilterBooleanOperators: UiInputProperty[] =
        [
            { name: 'Equal', value: 'eq' },
            { name: 'Not Equal', value: 'ne' },
            { name: 'In', value: 'in' },
            { name: 'Not In', value: 'not-in' },
            { name: 'Null', value: 'null' },
            { name: 'Not Null', value: 'not-null' },
        ];
    static readonly FilterDateTimeOperators: UiInputProperty[] =
        [
            { name: 'Equal', value: 'eq' },
            { name: 'Not Equal', value: 'ne' },
            { name: 'In', value: 'in' },
            { name: 'Not In', value: 'not-in' },
            { name: 'Null', value: 'null' },
            { name: 'Not Null', value: 'not-null' },
            { name: 'Between', value: 'between' },
            { name: 'Not Between', value: 'not-between' },
            { name: 'Greater Than', value: 'gt' },
            { name: 'Greater Equal', value: 'ge' },
            { name: 'Less Than', value: 'lt' },
            { name: 'Less Equal', value: 'le' },
            { name: 'In Fiscal Period', value: 'in-fiscal-period' },
            { name: 'In Fiscal Period Adn Year', value: 'in-fiscal-period-and-year' },
            { name: 'In Fiscal Year', value: 'in-fiscal-year' },
            { name: 'In Or After Fiscal Period And Year', value: 'in-or-after-fiscal-period-and-year' },
            { name: 'In Or Before Fiscal Period And Year', value: 'in-or-before-fiscal-period-and-year' },
            { name: 'Last 7 Days', value: 'last-seven-days' },
            { name: 'Last Fiscal Period', value: 'last-fiscal-period' },
            { name: 'Last Fiscal Year', value: 'last-fiscal-year' },
            { name: 'Last Month', value: 'last-month' },
            { name: 'Last Week', value: 'last-week' },
            { name: 'Last X Days', value: 'last-x-days' },
            { name: 'Last X Fiscal Periods', value: 'last-x-fiscal-periods' },
            { name: 'Last X Fiscal Years', value: 'last-x-fiscal-years' },
            { name: 'Last X Hours', value: 'last-x-hours' },
            { name: 'Last X Months', value: 'last-x-months' },
            { name: 'Last X Weeks', value: 'last-x-weeks' },
            { name: 'Last X Years', value: 'last-x-years' },
            { name: 'Last Year', value: 'last-year' },
            { name: 'Next 7 Days', value: 'next-seven-days' },
            { name: 'Next Fiscal Period', value: 'next-fiscal-period' },
            { name: 'Next Fiscal Year', value: 'next-fiscal-year' },
            { name: 'Next Month', value: 'next-month' },
            { name: 'Next Week', value: 'next-week' },
            { name: 'Next X Days', value: 'next-x-days' },
            { name: 'Next X Fiscal Periods', value: 'next-x-fiscal-periods' },
            { name: 'Next X Fiscal Years', value: 'next-x-fiscal-years' },
            { name: 'Next X Hours', value: 'next-x-hours' },
            { name: 'Next X Months', value: 'next-x-months' },
            { name: 'Next X Weeks', value: 'next-x-weeks' },
            { name: 'Next X Years', value: 'next-x-years' },
            { name: 'Next Year', value: 'next-year' },
            { name: 'Older Than X Years', value: 'olderthan-x-years' },
            { name: 'Older Than X Months', value: 'olderthan-x-months' },
            { name: 'Older Than X Weeks', value: 'olderthan-x-weeks' },
            { name: 'Older Than X Days', value: 'olderthan-x-days' },
            { name: 'Older Than X Hours', value: 'olderthan-x-hours' },
            { name: 'Older Than X Minutes', value: 'olderthan-x-minutes' },
            { name: 'On', value: 'on' },
            { name: 'On Or After', value: 'on-or-after' },
            { name: 'On Or Before', value: 'on-or-before' },
            { name: 'This Fiscal Period', value: 'this-fiscal-period' },
            { name: 'This Fiscal Year', value: 'this-fiscal-year' },
            { name: 'This Month', value: 'this-month' },
            { name: 'This Week', value: 'this-week' },
            { name: 'This Year', value: 'this-year' },
            { name: 'Today', value: 'today' },
            { name: 'Tomorrow', value: 'tomorrow' },
            { name: 'Yesterday', value: 'yesterday' },
            { name: 'Not On', value: 'not-on' },
        ];
    static readonly FilterNumberOperators: UiInputProperty[] =
        [
            { name: 'Equal', value: 'eq' },
            { name: 'Not Equal', value: 'neq' },
            { name: 'In', value: 'in' },
            { name: 'Not In', value: 'not-in' },
            { name: 'Null', value: 'null' },
            { name: 'Not Null', value: 'not-null' },
            { name: 'Between', value: 'between' },
            { name: 'Not Between', value: 'not-between' },
            { name: 'Greater Than', value: 'gt' },
            { name: 'Greater Equal', value: 'ge' },
            { name: 'Less Than', value: 'lt' },
            { name: 'Less Equal', value: 'le' },
        ];
    static readonly FilterStringOperators: UiInputProperty[] =
        [
            { name: 'Equal', value: 'eq' },
            { name: 'Not Equal', value: 'ne' },
            { name: 'In', value: 'in' },
            { name: 'Not In', value: 'not-in' },
            { name: 'Null', value: 'null' },
            { name: 'Not Null', value: 'not-null' },
            { name: 'Begins With', value: 'begins-with' },
            { name: 'Does Not Begin With', value: 'not-begin-with' },
            { name: 'Contains', value: 'contains' },
            { name: 'Does Not Contain', value: 'does-not-contain' },
            { name: 'Ends With', value: 'ends-with' },
            { name: 'Does Not End With', value: 'not-end-with' },
            { name: 'Like', value: 'like' },
            { name: 'Not Like', value: 'not-like' },
        ];
    static readonly FilterIdOperators: UiInputProperty[] =
        [
            { name: 'Equal', value: 'eq' },
            { name: 'Not Equal', value: 'ne' },
            { name: 'In', value: 'in' },
            { name: 'Not In', value: 'not-in' },
            { name: 'Null', value: 'null' },
            { name: 'Not Null', value: 'not-null' },
            { name: 'Above', value: 'above' },
            { name: 'Above Or Equal', value: 'eq-or-above' },
            { name: 'Under', value: 'under' },
            { name: 'Under Or Equal', value: 'eq-or-under' },
            { name: 'Not Under', value: 'not-under' },
            { name: 'Equal Business ID', value: 'eq-businessid' },
            { name: 'Not Equal Business ID', value: 'ne-businessid' },
            { name: 'Equal User ID', value: 'eq-userid' },
            { name: 'Not Equal User ID', value: 'ne-userid' },
        ];
    static readonly FilterPickListOperators: UiInputProperty[] =
        [
            { name: 'Equal', value: 'eq' },
            { name: 'Not Equal', value: 'ne' },
            { name: 'In', value: 'in' },
            { name: 'Not In', value: 'not-in' },
            { name: 'Null', value: 'null' },
            { name: 'Not Null', value: 'not-null' },
            { name: 'Between', value: 'between' },
            { name: 'Not Between', value: 'not-between' },
            { name: 'Greater Than', value: 'gt' },
            { name: 'Greater Equal', value: 'ge' },
            { name: 'Less Than', value: 'lt' },
            { name: 'Less Equal', value: 'le' },
        ];
}
