name: Count Lines of Code

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  count-lines-of-code:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install cloc
      run: |
        sudo apt-get update
        sudo apt-get install -y cloc

    - name: Count lines of code
      id: count
      run: |
        cloc --json . > cloc-output.json
        lines=$(jq '.SUM.code' < cloc-output.json)
        echo "lines=$lines" >> $GITHUB_ENV

    - name: Commit and push the result
      run: |
        echo "{\"lines\": \"$lines\"}" > lines-of-code.json
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add lines-of-code.json
        git commit -m "Update lines of code"
        git push
